In [3]:
#Importing the dependencies
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
#loading the datasets
df = pd.read_csv('SpotifyFeatures.csv')
df

,genre,artist_name,track_name,track_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,Movie,Henri Salvador,C'est beau de faire un Show,0BRjO6ga9RKCKjfDqeFgWV,0,0.61100,0.389,99373,0.910,0.000000,C#,0.3460,-1.828,Major,0.0525,166.969,4/4,0.814
1,Movie,Martin & les fées,Perdu d'avance (par Gad Elmaleh),0BjC1NfoEOOusryehmNudP,1,0.24600,0.590,137373,0.737,0.000000,F#,0.1510,-5.559,Minor,0.0868,174.003,4/4,0.816
2,Movie,Joseph Williams,Don't Let Me Be Lonely Tonight,0CoSDzoNIKCRs124s9uTVy,3,0.95200,0.663,170267,0.131,0.000000,C,0.1030,-13.879,Minor,0.0362,99.488,5/4,0.368
3,Movie,Henri Salvador,Dis-moi Monsieur Gordon Cooper,0Gc6TVm52BwZD07Ki6tIvf,0,0.70300,0.240,152427,0.326,0.000000,C#,0.0985,-12.178,Major,0.0395,171.758,4/4,0.227
4,Movie,Fabien Nataf,Ouverture,0IuslXpMROHdEPvSl1fTQK,4,0.95000,0.331,82625,0.225,0.123000,F,0.2020,-21.150,Major,0.0456,140.576,4/4,0.390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232720,Soul,Slave,Son Of Slide,2XGLdVl7lGeq8ksM6Al7jT,39,0.00384,0.687,326240,0.714,0.544000,D,0.0845,-10.626,Major,0.0316,115.542,4/4,0.962
232721,Soul,Jr Thomas & The Volcanos,Burning Fire,1qWZdkBl4UVPj9lK6HuuFM,38,0.03290,0.785,282447,0.683,0.000880,E,0.2370,-6.944,Minor,0.0337,113.830,4/4,0.969
232722,Soul,Muddy Waters,(I'm Your) Hoochie Coochie Man,2ziWXUmQLrXTiYjCg2fZ2t,47,0.90100,0.517,166960,0.419,0.000000,D,0.0945,-8.282,Major,0.1480,84.135,4/4,0.813
232723,Soul,R.LUM.R,With My Words,6EFsue2YbIG4Qkq8Zr9Rir,44,0.26200,0.745,222442,0.704,0.000000,A,0.3330,-7.137,Major,0.1460,100.031,4/4,0.489
232724,Soul,Mint Condition,You Don't Have To Hurt No More,34XO9RwPMKjbvRry54QzWn,35,0.09730,0.758,323027,0.470,0.000049,G#,0.0836,-6.708,Minor,0.0287,113.897,4/4,0.479

In [5]:
#shape
df.shape

(232725, 18)

In [6]:
#features
df.columns

Index(['genre', 'artist_name', 'track_name', 'track_id', 'popularity',
       'acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'key', 'liveness', 'loudness', 'mode',
       'speechiness', 'tempo', 'time_signature', 'valence'],
      dtype='object')

In [7]:
#viewing the top 5
df.head()

,genre,artist_name,track_name,track_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,Movie,Henri Salvador,C'est beau de faire un Show,0BRjO6ga9RKCKjfDqeFgWV,0,0.611,0.389,99373,0.910,0.000,C#,0.3460,-1.828,Major,0.0525,166.969,4/4,0.814
1,Movie,Martin & les fées,Perdu d'avance (par Gad Elmaleh),0BjC1NfoEOOusryehmNudP,1,0.246,0.590,137373,0.737,0.000,F#,0.1510,-5.559,Minor,0.0868,174.003,4/4,0.816
2,Movie,Joseph Williams,Don't Let Me Be Lonely Tonight,0CoSDzoNIKCRs124s9uTVy,3,0.952,0.663,170267,0.131,0.000,C,0.1030,-13.879,Minor,0.0362,99.488,5/4,0.368
3,Movie,Henri Salvador,Dis-moi Monsieur Gordon Cooper,0Gc6TVm52BwZD07Ki6tIvf,0,0.703,0.240,152427,0.326,0.000,C#,0.0985,-12.178,Major,0.0395,171.758,4/4,0.227
4,Movie,Fabien Nataf,Ouverture,0IuslXpMROHdEPvSl1fTQK,4,0.950,0.331,82625,0.225,0.123,F,0.2020,-21.150,Major,0.0456,140.576,4/4,0.390

In [8]:
#checking for the null and types of data present there.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232725 entries, 0 to 232724
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   genre             232725 non-null  object
 1   artist_name       232725 non-null  object
 2   track_name        232724 non-null  object
 3   track_id          232725 non-null  object
 4   popularity        232725 non-null  int64
 5   acousticness      232725 non-null  float64
 6   danceability      232725 non-null  float64
 7   duration_ms       232725 non-null  int64
 8   energy            232725 non-null  float64
 9   instrumentalness  232725 non-null  float64
 10  key               232725 non-null  object
 11  liveness          232725 non-null  float64
 12  loudness          232725 non-null  float64
 13  mode              232725 non-null  object
 14  speechiness       232725 non-null  float64
 15  tempo             232725 non-null  float64
 16  time_signature    232725 non-null  object
 17  valence           232725 non-null  float64
dtypes: float64(9), int64(2), object(7)
memory usage: 32.0+ MB

In [9]:
#stats
df.describe()

,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence
count,232725.000000,232725.000000,232725.000000,2.327250e+05,232725.000000,232725.000000,232725.000000,232725.000000,232725.000000,232725.000000,232725.000000
mean,41.127502,0.368560,0.554364,2.351223e+05,0.570958,0.148301,0.215009,-9.569885,0.120765,117.666585,0.454917
std,18.189948,0.354768,0.185608,1.189359e+05,0.263456,0.302768,0.198273,5.998204,0.185518,30.898907,0.260065
min,0.000000,0.000000,0.056900,1.538700e+04,0.000020,0.000000,0.009670,-52.457000,0.022200,30.379000,0.000000
25%,29.000000,0.037600,0.435000,1.828570e+05,0.385000,0.000000,0.097400,-11.771000,0.036700,92.959000,0.237000
50%,43.000000,0.232000,0.571000,2.204270e+05,0.605000,0.000044,0.128000,-7.762000,0.050100,115.778000,0.444000
75%,55.000000,0.722000,0.692000,2.657680e+05,0.787000,0.035800,0.264000,-5.501000,0.105000,139.054000,0.660000
max,100.000000,0.996000,0.989000,5.552917e+06,0.999000,0.999000,1.000000,3.744000,0.967000,242.903000,1.000000

In [10]:
#checking for null
df.isna().sum()

genre               0
artist_name         0
track_name          1
track_id            0
popularity          0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
speechiness         0
tempo               0
time_signature      0
valence             0
dtype: int64

In [11]:
#dropping the null values rows
df.dropna(inplace= True)
df.isna().sum()

genre               0
artist_name         0
track_name          0
track_id            0
popularity          0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
speechiness         0
tempo               0
time_signature      0
valence             0
dtype: int64

In [12]:
#checking for the duplicates
df.duplicated().sum()

0

In [13]:
df = df.drop_duplicates(subset=['track_name', 'artist_name']).copy()

### SOME Questions:

1. Which artists appears most frequently?

In [14]:
df.columns

Index(['genre', 'artist_name', 'track_name', 'track_id', 'popularity',
       'acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'key', 'liveness', 'loudness', 'mode',
       'speechiness', 'tempo', 'time_signature', 'valence'],
      dtype='object')

In [15]:
df.groupby("artist_name")['track_id'].count().sort_values(ascending= False).head()

artist_name
Giuseppe Verdi             1312
Giacomo Puccini            1094
Kimbo Children's Music      971
Wolfgang Amadeus Mozart     800
Richard Wagner              778
Name: track_id, dtype: int64

2. What are the top 10 most popular songs?

In [16]:
df.head()

,genre,artist_name,track_name,track_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,Movie,Henri Salvador,C'est beau de faire un Show,0BRjO6ga9RKCKjfDqeFgWV,0,0.611,0.389,99373,0.910,0.000,C#,0.3460,-1.828,Major,0.0525,166.969,4/4,0.814
1,Movie,Martin & les fées,Perdu d'avance (par Gad Elmaleh),0BjC1NfoEOOusryehmNudP,1,0.246,0.590,137373,0.737,0.000,F#,0.1510,-5.559,Minor,0.0868,174.003,4/4,0.816
2,Movie,Joseph Williams,Don't Let Me Be Lonely Tonight,0CoSDzoNIKCRs124s9uTVy,3,0.952,0.663,170267,0.131,0.000,C,0.1030,-13.879,Minor,0.0362,99.488,5/4,0.368
3,Movie,Henri Salvador,Dis-moi Monsieur Gordon Cooper,0Gc6TVm52BwZD07Ki6tIvf,0,0.703,0.240,152427,0.326,0.000,C#,0.0985,-12.178,Major,0.0395,171.758,4/4,0.227
4,Movie,Fabien Nataf,Ouverture,0IuslXpMROHdEPvSl1fTQK,4,0.950,0.331,82625,0.225,0.123,F,0.2020,-21.150,Major,0.0456,140.576,4/4,0.390

In [17]:
df.sort_values(by = 'popularity', 
               ascending= False).drop_duplicates(subset = ['track_name','artist_name','popularity'])[['track_name','artist_name','popularity']].head(10)

,track_name,artist_name,popularity
9027,7 rings,Ariana Grande,100
9026,"break up with your girlfriend, i'm bored",Ariana Grande,99
86951,Wow.,Post Malone,99
66643,Con Calma,Daddy Yankee,98
9028,Without Me,Halsey,97
107875,Calma - Remix,Pedro Capó,97
9037,Sweet but Psycho,Ava Max,97
107812,Happier,Marshmello,97
107810,Dancing With A Stranger (with Normani),Sam Smith,97
86953,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,97

3. Which genres contains the most songs?

In [18]:
df.groupby('genre')['track_id'].count().sort_values(ascending= False).head()

genre
Comedy         9674
Electronic     9150
Alternative    9098
Anime          8935
Classical      8703
Name: track_id, dtype: int64

4. Which artists have the highest average popularity

In [19]:
df.groupby('artist_name').agg(
    avg_popularity = ('popularity','mean'),
    num_songs = ('track_name','count')).sort_values(by ='avg_popularity',
                                                    ascending = False).head(10)

                      avg_popularity  num_songs
artist_name
Pedro Capó                 87.000000          2
Mario Bautista             85.000000          1
Mau y Ricky                83.000000          2
Kris Kross Amsterdam       82.000000          1
Ninho                      82.000000          1
Martin Garrix              81.857143          7
Sofia Reyes                81.000000          1
Kenny Man                  81.000000          2
Paloma Mami                81.000000          2
Anitta                     81.000000          3

8. Which genre has the highest average popularity?

In [20]:
df.groupby('genre')['popularity'].mean().sort_values(ascending = False).head(1)

genre
Pop    67.069295
Name: popularity, dtype: float64

In [21]:
#or can do 
df.groupby('genre').agg( avg_popularity = 
                        ('popularity','mean')).sort_values(
                            by = 'avg_popularity',ascending = False).head(1)

       avg_popularity
genre
Pop         67.069295

9. Which songs are longer than the average duration?

In [22]:
avg_duration =df['duration_ms'].mean()
print(avg_duration.round(2))

df[df['duration_ms'] >= avg_duration][['track_name','duration_ms']].head()

236153.36

                                           track_name  duration_ms
7                                       Let Me Let Go       240067
10  Symphony No.4 In E Minor Op.98 : IV. Allegro E...       566960
13                                      Mangala Aarti       308627
15       Les aventures d'Arsène Lupin: 813 - Partie 6      2447870
16                                              Diane       523424

10. Which genres have the longest average songs?

In [23]:
df.groupby('genre')['duration_ms'].mean().sort_values(ascending =False).head(1)

genre
World    316312.525
Name: duration_ms, dtype: float64

## Intermediate level

1. Which artist has released the most songs in each genre?

In [24]:
top_artists_by_genre = (
    df.groupby(['genre', 'artist_name'])['track_id']
      .count()
      .reset_index(name='song_count')
      .sort_values(['genre', 'song_count'], ascending=[True, False])
      .drop_duplicates(subset='genre')
)

print(top_artists_by_genre)

                  genre               artist_name  song_count
6             A Capella     The Singers Unlimited          36
441         Alternative   Five Finger Death Punch          82
1634              Anime             Nobuo Uematsu         772
2397              Blues                     Phish         152
2831   Children's Music    Kimbo Children's Music         971
3062   Children’s Music           Hillsong UNITED          56
3970          Classical   Wolfgang Amadeus Mozart         800
4100             Comedy             George Carlin         215
4581            Country             George Strait         145
5317              Dance               Chris Brown         123
6384         Electronic                      Moby         154
6790               Folk                 Bob Dylan          80
8092            Hip-Hop                    Eminem         172
8769              Indie            Arctic Monkeys          72
10631              Jazz               Miles Davis          93
11444             Movie              Randy Newman         667
11590             Opera            Giuseppe Verdi        1312
11770               Pop                       BTS          76
12674               R&B            Eric Bellinger          64
13458               Rap                Kanye West          82
13707            Reggae  Bob Marley & The Wailers         380
14379         Reggaeton              Daddy Yankee         174
15134              Rock               The Beatles         145
15403               Ska                      NOFX         277
15647              Soul             Amy Winehouse          72
16595        Soundtrack               Hans Zimmer         559
16969             World          Hillsong Worship         289

In [25]:
df.columns

Index(['genre', 'artist_name', 'track_name', 'track_id', 'popularity',
       'acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'key', 'liveness', 'loudness', 'mode',
       'speechiness', 'tempo', 'time_signature', 'valence'],
      dtype='object')

12. Which artists have above-average popularity?

In [27]:
overall_avg_popularity = df['popularity'].mean()
print(overall_avg_popularity)

36.257590092514434

In [30]:
#filtering these artists
above_average_artists = (
    df.groupby('artist_name')['popularity'].mean()
    .loc[lambda x:x> overall_avg_popularity]
    .sort_values(ascending= False)
)
print(above_average_artists)

artist_name
Pedro Capó              87.000000
Mario Bautista          85.000000
Mau y Ricky             83.000000
Ninho                   82.000000
Kris Kross Amsterdam    82.000000
                          ...
Capital City Music      36.285714
Babe Rainbow            36.280000
Red Rocks Worship       36.269231
Hillsong UNITED         36.262673
GTA                     36.260870
Name: popularity, Length: 9899, dtype: float64

13. Find the top 5 songs within each genre.

In [37]:
top_5 = (
    df.sort_values('popularity',ascending = False)
    .groupby('genre').head(5)
)
print(top_5)

           genre            artist_name  \
9027       Dance          Ariana Grande
9026       Dance          Ariana Grande
86951        Rap            Post Malone
66643    Hip-Hop           Daddy Yankee
9028       Dance                 Halsey
...          ...                    ...
552    A Capella         MC6 A Cappella
553    A Capella  The Singers Unlimited
555    A Capella         MC6 A Cappella
554    A Capella         MC6 A Cappella
556    A Capella                   Glad

                                     track_name                track_id  \
9027                                    7 rings  14msK75pk3pA33pzPVNtBF
9026   break up with your girlfriend, i'm bored  4kV4N9D1iKVxx1KLvtTpjS
86951                                      Wow.  6MWtB6iiXyIwun0YzU6DFP
66643                                 Con Calma  5w9c2J52mkdntKOmRLeM2m
9028                                 Without Me  5p7ujcrUXASCNwRaWNHR1C
...                                         ...                     ...
552                        For the Longest Time  0PuWvFJqZPJAxZNrFgw8xL
553                                       Clair  1iXJKuzDH0E6PnTk2lQXAq
555                     The Lion Sleeps Tonight  0crWDkAajRTnsGuZ6CAU85
554                             Come Go With Me  3XxwdU13609bTGaAFRg3PA
556                     A Debtor to Mercy Alone  6TK4I15u1oym5H2eETng4F

       popularity  acousticness  danceability  duration_ms  energy  \
9027          100        0.5780         0.725       178640   0.321
9026           99        0.0421         0.726       190440   0.554
86951          99        0.1630         0.833       149520   0.539
66643          98        0.1100         0.737       193227   0.860
9028           97        0.2970         0.752       201661   0.488
...           ...           ...           ...          ...     ...
552            44        0.7800         0.616       223813   0.298
553            33        0.9730         0.484       154200   0.222
555            26        0.3020         0.691       183920   0.490
554            25        0.8020         0.717       137800   0.518
556            24        0.5990         0.389       181267   0.153

       instrumentalness key  liveness  loudness   mode  speechiness    tempo  \
9027           0.000000  C#    0.0884   -10.744  Minor       0.3230   70.142
9026           0.000000   F    0.1060    -5.290  Minor       0.0917  169.999
86951          0.000002   B    0.1010    -7.399  Minor       0.1780   99.947
66643          0.000002  G#    0.0574    -2.652  Minor       0.0593   93.989
9028           0.000009  F#    0.0936    -7.050  Major       0.0705  136.041
...                 ...  ..       ...       ...    ...          ...      ...
552            0.000000   D    0.0973    -7.712  Major       0.0274   82.471
553            0.000306   F    0.1040   -14.631  Minor       0.0440  127.689
555            0.000006   F    0.2290   -11.222  Major       0.0743  107.066
554            0.000000  G#    0.0940    -7.754  Major       0.0883  129.878
556            0.000000   E    0.0902   -12.023  Major       0.0430  120.626

      time_signature  valence  popularity_rank
9027             4/4    0.319              1.0
9026             4/4    0.335              2.0
86951            4/4    0.385              1.0
66643            4/4    0.656              1.0
9028             4/4    0.533              3.0
...              ...      ...              ...
552              4/4    0.712              1.0
553              4/4    0.409              2.0
555              4/4    0.664              3.0
554              4/4    0.672              4.0
556              4/4    0.236              5.0

[135 rows x 19 columns]

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

14. Which genres are the most danceable?

In [39]:
genre_rank = (
    df.groupby('genre')['popularity']
      .mean()
      .rank(ascending=False, method='dense')
)

df['dance_rank'] = df['genre'].map(genre_rank)

print(df[['dance_rank', 'genre', 'popularity']].head())

   dance_rank  genre  popularity
0        25.0  Movie           0
1        25.0  Movie           1
2        25.0  Movie           3
3        25.0  Movie           0
4        25.0  Movie           4